fold_0:
  test:
  - ball_base
  - basket_cylinder
  - bigstuffedanimal_bear
  - bottle_fuse
  - can_arizona
  - cannedfood_chili
  - cone_1
  - cup_blue
  - egg_cardboard
  - eggcoloringcup_blue
  - medicine_ampicillin
  - metal_flower_cylinder
  - noodle_1
  - pasta_cremette
  - pvc_1
  - smallstuffedanimal_bunny
  - timber_pentagon
  - tin_pokemon
  - tupperware_coffee_beans
  - weight_1
  train:
  - ball_basket
  - ball_blue
  - ball_transparent
  - ball_yellow_purple
  - basket_funnel
  - basket_green
  - basket_handle
  - basket_semicircle
  - bigstuffedanimal_bunny
  - bigstuffedanimal_frog
  - bigstuffedanimal_pink_dog
  - bigstuffedanimal_tan_dog
  - bottle_google
  - bottle_green
  - bottle_red
  - bottle_sobe
  - can_coke
  - can_red_bull_large
  - can_red_bull_small
  - can_starbucks
  - cannedfood_cowboy_cookout
  - cannedfood_soup
  - cannedfood_tomato_paste
  - cannedfood_tomatoes
  - cone_2
  - cone_3
  - cone_4
  - cone_5
  - cup_isu
  - cup_metal
  - cup_paper_green
  - cup_yellow
  - egg_plastic_wrap
  - egg_rough_styrofoam
  - egg_smooth_styrofoam
  - egg_wood
  - eggcoloringcup_green
  - eggcoloringcup_orange
  - eggcoloringcup_pink
  - eggcoloringcup_yellow
  - medicine_aspirin
  - medicine_bilberry_extract
  - medicine_calcium
  - medicine_flaxseed_oil
  - metal_food_can
  - metal_mix_covered_cup
  - metal_tea_jar
  - metal_thermos
  - noodle_2
  - noodle_3
  - noodle_4
  - noodle_5
  - pasta_macaroni
  - pasta_penne
  - pasta_pipette
  - pasta_rotini
  - pvc_2
  - pvc_3
  - pvc_4
  - pvc_5
  - smallstuffedanimal_chick
  - smallstuffedanimal_headband_bear
  - smallstuffedanimal_moose
  - smallstuffedanimal_otter
  - timber_rectangle
  - timber_semicircle
  - timber_square
  - timber_squiggle
  - tin_poker
  - tin_snack_depot
  - tin_snowman
  - tin_tea
  - tupperware_ground_coffee
  - tupperware_marbles
  - tupperware_pasta
  - tupperware_rice
  - weight_2
  - weight_3
  - weight_4
  - weight_5
fold_1:
  test:
  - ball_basket
  - basket_funnel
  - bigstuffedanimal_bunny
  - bottle_google
  - can_coke
  - cannedfood_cowboy_cookout
  - cone_2
  - cup_isu
  - egg_plastic_wrap
  - eggcoloringcup_green
  - medicine_aspirin
  - metal_food_can
  - noodle_2
  - pasta_macaroni
  - pvc_2
  - smallstuffedanimal_chick
  - timber_rectangle
  - tin_poker
  - tupperware_ground_coffee
  - weight_2
  train:
  - ball_base
  - ball_blue
  - ball_transparent
  - ball_yellow_purple
  - basket_cylinder
  - basket_green
  - basket_handle
  - basket_semicircle
  - bigstuffedanimal_bear
  - bigstuffedanimal_frog
  - bigstuffedanimal_pink_dog
  - bigstuffedanimal_tan_dog
  - bottle_fuse
  - bottle_green
  - bottle_red
  - bottle_sobe
  - can_arizona
  - can_red_bull_large
  - can_red_bull_small
  - can_starbucks
  - cannedfood_chili
  - cannedfood_soup
  - cannedfood_tomato_paste
  - cannedfood_tomatoes
  - cone_1
  - cone_3
  - cone_4
  - cone_5
  - cup_blue
  - cup_metal
  - cup_paper_green
  - cup_yellow
  - egg_cardboard
  - egg_rough_styrofoam
  - egg_smooth_styrofoam
  - egg_wood
  - eggcoloringcup_blue
  - eggcoloringcup_orange
  - eggcoloringcup_pink
  - eggcoloringcup_yellow
  - medicine_ampicillin
  - medicine_bilberry_extract
  - medicine_calcium
  - medicine_flaxseed_oil
  - metal_flower_cylinder
  - metal_mix_covered_cup
  - metal_tea_jar
  - metal_thermos
  - noodle_1
  - noodle_3
  - noodle_4
  - noodle_5
  - pasta_cremette
  - pasta_penne
  - pasta_pipette
  - pasta_rotini
  - pvc_1
  - pvc_3
  - pvc_4
  - pvc_5
  - smallstuffedanimal_bunny
  - smallstuffedanimal_headband_bear
  - smallstuffedanimal_moose
  - smallstuffedanimal_otter
  - timber_pentagon
  - timber_semicircle
  - timber_square
  - timber_squiggle
  - tin_pokemon
  - tin_snack_depot
  - tin_snowman
  - tin_tea
  - tupperware_coffee_beans
  - tupperware_marbles
  - tupperware_pasta
  - tupperware_rice
  - weight_1
  - weight_3
  - weight_4
  - weight_5
fold_2:
  test:
  - ball_blue
  - basket_green
  - bigstuffedanimal_frog
  - bottle_green
  - can_red_bull_large
  - cannedfood_soup
  - cone_3
  - cup_metal
  - egg_rough_styrofoam
  - eggcoloringcup_orange
  - medicine_bilberry_extract
  - metal_mix_covered_cup
  - noodle_3
  - pasta_penne
  - pvc_3
  - smallstuffedanimal_headband_bear
  - timber_semicircle
  - tin_snack_depot
  - tupperware_marbles
  - weight_3
  train:
  - ball_base
  - ball_basket
  - ball_transparent
  - ball_yellow_purple
  - basket_cylinder
  - basket_funnel
  - basket_handle
  - basket_semicircle
  - bigstuffedanimal_bear
  - bigstuffedanimal_bunny
  - bigstuffedanimal_pink_dog
  - bigstuffedanimal_tan_dog
  - bottle_fuse
  - bottle_google
  - bottle_red
  - bottle_sobe
  - can_arizona
  - can_coke
  - can_red_bull_small
  - can_starbucks
  - cannedfood_chili
  - cannedfood_cowboy_cookout
  - cannedfood_tomato_paste
  - cannedfood_tomatoes
  - cone_1
  - cone_2
  - cone_4
  - cone_5
  - cup_blue
  - cup_isu
  - cup_paper_green
  - cup_yellow
  - egg_cardboard
  - egg_plastic_wrap
  - egg_smooth_styrofoam
  - egg_wood
  - eggcoloringcup_blue
  - eggcoloringcup_green
  - eggcoloringcup_pink
  - eggcoloringcup_yellow
  - medicine_ampicillin
  - medicine_aspirin
  - medicine_calcium
  - medicine_flaxseed_oil
  - metal_flower_cylinder
  - metal_food_can
  - metal_tea_jar
  - metal_thermos
  - noodle_1
  - noodle_2
  - noodle_4
  - noodle_5
  - pasta_cremette
  - pasta_macaroni
  - pasta_pipette
  - pasta_rotini
  - pvc_1
  - pvc_2
  - pvc_4
  - pvc_5
  - smallstuffedanimal_bunny
  - smallstuffedanimal_chick
  - smallstuffedanimal_moose
  - smallstuffedanimal_otter
  - timber_pentagon
  - timber_rectangle
  - timber_square
  - timber_squiggle
  - tin_pokemon
  - tin_poker
  - tin_snowman
  - tin_tea
  - tupperware_coffee_beans
  - tupperware_ground_coffee
  - tupperware_pasta
  - tupperware_rice
  - weight_1
  - weight_2
  - weight_4
  - weight_5
fold_3:
  test:
  - ball_transparent
  - basket_handle
  - bigstuffedanimal_pink_dog
  - bottle_red
  - can_red_bull_small
  - cannedfood_tomato_paste
  - cone_4
  - cup_paper_green
  - egg_smooth_styrofoam
  - eggcoloringcup_pink
  - medicine_calcium
  - metal_tea_jar
  - noodle_4
  - pasta_pipette
  - pvc_4
  - smallstuffedanimal_moose
  - timber_square
  - tin_snowman
  - tupperware_pasta
  - weight_4
  train:
  - ball_base
  - ball_basket
  - ball_blue
  - ball_yellow_purple
  - basket_cylinder
  - basket_funnel
  - basket_green
  - basket_semicircle
  - bigstuffedanimal_bear
  - bigstuffedanimal_bunny
  - bigstuffedanimal_frog
  - bigstuffedanimal_tan_dog
  - bottle_fuse
  - bottle_google
  - bottle_green
  - bottle_sobe
  - can_arizona
  - can_coke
  - can_red_bull_large
  - can_starbucks
  - cannedfood_chili
  - cannedfood_cowboy_cookout
  - cannedfood_soup
  - cannedfood_tomatoes
  - cone_1
  - cone_2
  - cone_3
  - cone_5
  - cup_blue
  - cup_isu
  - cup_metal
  - cup_yellow
  - egg_cardboard
  - egg_plastic_wrap
  - egg_rough_styrofoam
  - egg_wood
  - eggcoloringcup_blue
  - eggcoloringcup_green
  - eggcoloringcup_orange
  - eggcoloringcup_yellow
  - medicine_ampicillin
  - medicine_aspirin
  - medicine_bilberry_extract
  - medicine_flaxseed_oil
  - metal_flower_cylinder
  - metal_food_can
  - metal_mix_covered_cup
  - metal_thermos
  - noodle_1
  - noodle_2
  - noodle_3
  - noodle_5
  - pasta_cremette
  - pasta_macaroni
  - pasta_penne
  - pasta_rotini
  - pvc_1
  - pvc_2
  - pvc_3
  - pvc_5
  - smallstuffedanimal_bunny
  - smallstuffedanimal_chick
  - smallstuffedanimal_headband_bear
  - smallstuffedanimal_otter
  - timber_pentagon
  - timber_rectangle
  - timber_semicircle
  - timber_squiggle
  - tin_pokemon
  - tin_poker
  - tin_snack_depot
  - tin_tea
  - tupperware_coffee_beans
  - tupperware_ground_coffee
  - tupperware_marbles
  - tupperware_rice
  - weight_1
  - weight_2
  - weight_3
  - weight_5
fold_4:
  test:
  - ball_yellow_purple
  - basket_semicircle
  - bigstuffedanimal_tan_dog
  - bottle_sobe
  - can_starbucks
  - cannedfood_tomatoes
  - cone_5
  - cup_yellow
  - egg_wood
  - eggcoloringcup_yellow
  - medicine_flaxseed_oil
  - metal_thermos
  - noodle_5
  - pasta_rotini
  - pvc_5
  - smallstuffedanimal_otter
  - timber_squiggle
  - tin_tea
  - tupperware_rice
  - weight_5
  train:
  - ball_base
  - ball_basket
  - ball_blue
  - ball_transparent
  - basket_cylinder
  - basket_funnel
  - basket_green
  - basket_handle
  - bigstuffedanimal_bear
  - bigstuffedanimal_bunny
  - bigstuffedanimal_frog
  - bigstuffedanimal_pink_dog
  - bottle_fuse
  - bottle_google
  - bottle_green
  - bottle_red
  - can_arizona
  - can_coke
  - can_red_bull_large
  - can_red_bull_small
  - cannedfood_chili
  - cannedfood_cowboy_cookout
  - cannedfood_soup
  - cannedfood_tomato_paste
  - cone_1
  - cone_2
  - cone_3
  - cone_4
  - cup_blue
  - cup_isu
  - cup_metal
  - cup_paper_green
  - egg_cardboard
  - egg_plastic_wrap
  - egg_rough_styrofoam
  - egg_smooth_styrofoam
  - eggcoloringcup_blue
  - eggcoloringcup_green
  - eggcoloringcup_orange
  - eggcoloringcup_pink
  - medicine_ampicillin
  - medicine_aspirin
  - medicine_bilberry_extract
  - medicine_calcium
  - metal_flower_cylinder
  - metal_food_can
  - metal_mix_covered_cup
  - metal_tea_jar
  - noodle_1
  - noodle_2
  - noodle_3
  - noodle_4
  - pasta_cremette
  - pasta_macaroni
  - pasta_penne
  - pasta_pipette
  - pvc_1
  - pvc_2
  - pvc_3
  - pvc_4
  - smallstuffedanimal_bunny
  - smallstuffedanimal_chick
  - smallstuffedanimal_headband_bear
  - smallstuffedanimal_moose
  - timber_pentagon
  - timber_rectangle
  - timber_semicircle
  - timber_square
  - tin_pokemon
  - tin_poker
  - tin_snack_depot
  - tin_snowman
  - tupperware_coffee_beans
  - tupperware_ground_coffee
  - tupperware_marbles
  - tupperware_pasta
  - weight_1
  - weight_2
  - weight_3
  - weight_4
